/**
 * Generates seed/seed.sql: NON-CONFIDENTIAL demo data for dev and staging.
 * Mirrors the Claude Design prototype (78 approved signals, 4 Inbox drafts,
 * capture log) plus a second tenant used to demonstrate tenant isolation.
 * Every third signal and two of the drafts belong to the Secondary stream, so
 * both Trackers, both Inboxes and Phantoms have data.
 *
 * Matches the manual-entry prototype: Inbox drafts arrive with every tracker
 * field empty (with a saved copy of the page to read) and published signals
 * were entered by analysts. No AI/LLM output is seeded.
 *
 * Dates are SQL expressions relative to the moment the seed is applied, so the
 * default "last 3 months" dashboard view always has data.
 *
 *   npm run seed:generate -w apps/api   # regenerate seed.sql
 *   npm run db:seed:local               # apply to the local D1 database
 *
 * Never run against production.
 */
import { writeFileSync } from "node:fs";
import { DEFAULT_KEYS, SOURCE_TIER, STREAMS, defaultSchema, type Stream } from "@eradigm/shared";
import { canonicalJson } from "../src/lib/crypto.js";
import { createHash, createHmac } from "node:crypto";

// Taxonomy and options are the same in both streams; columns differ (see defaultColumns).
const schema = defaultSchema("secondary");
const MAC = Object.fromEntries(schema.taxonomy.map((g) => [g.name, g.subtrends]));
const MACROS = Object.keys(MAC);
const ALLSUBS = MACROS.flatMap((m) => MAC[m] as string[]);
const PH = [
  "unveils in-house generative chemistry platform", "commissions new AI supercomputer for R&D", "signs multi-year AI discovery partnership", "restructures R&D sites around an AI-first model", "pilots agentic AI across early research workflows",
  "launches tiered AI accreditation for all staff", "hosts company-wide AI festival and hackathon", "opens internal AI enablement storefront", "rolls out function-specific AI upskilling tracks", "reports most employees now use GenAI weekly", "names executive-led AI champions network", "appoints first Chief AI Officer",
  "commits $1bn to enterprise digital transformation", "expands enterprise cloud partnership", "wins industry award for digital innovation", "uses LLMs to draft regulatory submissions", "cuts trial enrolment time with AI site selection", "deploys AI next-best-action for field teams",
  "launches direct-to-patient program", "publishes cash prices on its DTP platform", "extends DTP offering to European markets", "builds unified DTP platform with telehealth partners", "brings DTP offering to a national retail pharmacy chain", "partners with creator network on patient campaign", "faces regulator scrutiny over DTC advertising", "signs direct-to-employer agreement",
  "responds to IRA negotiated price list", "bypasses PBMs with direct pricing model", "agrees acquisition of AI-enabled biotech", "licenses AI-designed asset in co-development deal", "pilots clinical decision support LLM with health system", "optimises medical content for generative search engines", "opens robotics-enabled autonomous lab", "releases open-source biology foundation model", "comments on sector outlook at investor day",
];
const PHRASE: Record<string, string> = {};
ALLSUBS.forEach((s, i) => (PHRASE[s] = PH[i] as string));
const COMPS = ["Pfizer", "Novartis", "Roche", "Sanofi", "AstraZeneca"];
const SOURCES = ["LinkedIn", "PR", "Publication", "Primary Source", "Client Signals"];
const GROWTH = ["Stable", "Slight Increase", "Strong Increase"];
const IMPACT = ["Low", "Medium", "High"];

function rng(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const q = (v: unknown): string => (v == null ? "NULL" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const daysAgo = (n: number) => `date('now', '-${n} days')`;
const mod = (n: number, unit: string) => `'${n <= 0 ? "+" : "-"}${Math.abs(n)} ${unit}'`;
const tsAgo = (days: number, minutes = 0) => `strftime('%Y-%m-%dT%H:%M:%fZ', 'now', ${mod(days, "days")}, ${mod(minutes, "minutes")})`;

const out: string[] = ["-- GENERATED by seed/generate-seed.ts — non-confidential demo data. Do not apply to production.", "PRAGMA foreign_keys = ON;"];
const GEN_AT = new Date().toISOString();

// ---------------------------------------------------------------------------
// Tenants, schema, settings, users
// ---------------------------------------------------------------------------
const TENANTS = [
  { id: "t_demo", name: "Eradigm Demo Client", slug: "demo" },
  { id: "t_north", name: "Northwind Pharma (demo)", slug: "northwind" },
];
const DEFAULT_SETTINGS = {
  timezone: "Europe/London",
  trendDefaults: { minSampleSize: 5, signalCountChangePct: 25, distinctCompetitorsChange: 1, impactScoreChangePct: 25, growthScoreChange: 0.2 },
  retention: { snapshotDays: 730, rejectedDays: 90, deletedDays: 30 },
  redaction: { redactEmails: true, redactPhones: true, quarantineMarkers: [] },
  phantoms: { secondaryMinImpact: "Low" },
};
let optN = 0;
for (const t of TENANTS) {
  out.push(`INSERT INTO tenants (id, name, slug, created_at) VALUES (${q(t.id)}, ${q(t.name)}, ${q(t.slug)}, ${q(GEN_AT)});`);
  out.push(`INSERT INTO schema_meta (tenant_id, revision) VALUES (${q(t.id)}, 1);`);
  out.push(`INSERT INTO tenant_settings (tenant_id, settings_json, updated_at) VALUES (${q(t.id)}, ${q(JSON.stringify(DEFAULT_SETTINGS))}, ${q(GEN_AT)});`);
  for (const st of STREAMS) {
    for (const c of defaultSchema(st).columns) {
      out.push(
        `INSERT INTO tracker_columns (tenant_id, stream, key, label, type, core, required, ai_assist, in_tracker, position, tracker_position, in_phantoms, phantoms_position) VALUES (${q(t.id)}, '${st}', ${q(c.key)}, ${q(c.label)}, ${q(c.type)}, ${c.core ? 1 : 0}, ${c.required ? 1 : 0}, ${c.aiAssist ? 1 : 0}, ${c.inTracker ? 1 : 0}, ${c.position}, ${c.trackerPosition}, ${c.inPhantoms ? 1 : 0}, ${c.phantomsPosition});`,
      );
      (c.options ?? []).forEach((o, i) =>
        out.push(`INSERT INTO column_options (id, tenant_id, stream, column_key, value, parent, position, created_at) VALUES ('opt_seed${++optN}', ${q(t.id)}, '${st}', ${q(c.key)}, ${q(o)}, NULL, ${i}, ${q(GEN_AT)});`),
      );
    }
    schema.taxonomy.forEach((g, i) => {
      out.push(`INSERT INTO column_options (id, tenant_id, stream, column_key, value, parent, position, created_at) VALUES ('opt_seed${++optN}', ${q(t.id)}, '${st}', 'macrotrend', ${q(g.name)}, NULL, ${i}, ${q(GEN_AT)});`);
      g.subtrends.forEach((s, j) =>
        out.push(`INSERT INTO column_options (id, tenant_id, stream, column_key, value, parent, position, created_at) VALUES ('opt_seed${++optN}', ${q(t.id)}, '${st}', 'subtrend', ${q(s)}, ${q(g.name)}, ${j}, ${q(GEN_AT)});`),
      );
    });
  }
}

const USERS = [
  { id: "u_admin", email: "admin@example.com", name: "E. Admin", tenant: "t_demo", role: "admin" },
  { id: "u_lg", email: "l.griffith@example.com", name: "L. Griffith", tenant: "t_demo", role: "analyst" },
  { id: "u_ap", email: "a.patel@example.com", name: "A. Patel", tenant: "t_demo", role: "analyst" },
  { id: "u_jm", email: "j.morgan@example.com", name: "J. Morgan", tenant: "t_demo", role: "analyst" },
  { id: "u_so", email: "s.okafor@example.com", name: "S. Okafor", tenant: "t_demo", role: "analyst" },
  { id: "u_client", email: "client@example.com", name: "C. Client", tenant: "t_demo", role: "client" },
  { id: "u_north_an", email: "analyst@northwind.example.com", name: "N. Analyst", tenant: "t_north", role: "analyst" },
  { id: "u_north_ad", email: "admin@northwind.example.com", name: "N. Admin", tenant: "t_north", role: "admin" },
];
for (const u of USERS) {
  out.push(`INSERT INTO users (id, email, name, created_at) VALUES (${q(u.id)}, ${q(u.email)}, ${q(u.name)}, ${q(GEN_AT)});`);
  out.push(`INSERT INTO role_assignments (id, tenant_id, user_id, role, assigned_at) VALUES ('rol_${u.id}', ${q(u.tenant)}, ${q(u.id)}, ${q(u.role)}, ${q(GEN_AT)});`);
}
// L. Griffith also works on the Northwind workspace (multi-tenant analyst).
out.push(`INSERT INTO role_assignments (id, tenant_id, user_id, role, assigned_at) VALUES ('rol_u_lg_north', 't_north', 'u_lg', 'analyst', ${q(GEN_AT)});`);

// ---------------------------------------------------------------------------
// Audit chain (computed here so seeded items also have an audit trail)
// ---------------------------------------------------------------------------
const chainHead: Record<string, string> = {};
let auditN = 0;
function auditEvent(tenant: string, actor: { id: string; email: string } | null, action: string, targetType: string, targetId: string, details: Record<string, unknown>) {
  const row = {
    id: `aud_seed${String(++auditN).padStart(5, "0")}`,
    chain: tenant,
    tenant_id: tenant,
    at: new Date(Date.parse(GEN_AT) + auditN).toISOString(),
    actor_id: actor?.id ?? null,
    actor_email: actor?.email ?? "system",
    action,
    target_type: targetType,
    target_id: targetId,
    details,
    prev_hash: chainHead[tenant] ?? "genesis",
  };
  // Must match services/audit.ts: HMAC-SHA256 with AUDIT_HMAC_KEY when set, else plain SHA-256.
  // For staging, generate with the same key the environment uses: AUDIT_HMAC_KEY=... npm run seed:generate
  const key = process.env.AUDIT_HMAC_KEY;
  const hash = key ? createHmac("sha256", Buffer.from(key, "base64")).update(canonicalJson(row)).digest("hex") : createHash("sha256").update(canonicalJson(row)).digest("hex");
  chainHead[tenant] = hash;
  out.push(
    `INSERT INTO audit_events (id, chain, tenant_id, at, actor_id, actor_email, action, target_type, target_id, details_json, prev_hash, hash) VALUES (${q(row.id)}, ${q(tenant)}, ${q(tenant)}, ${q(row.at)}, ${q(row.actor_id)}, ${q(row.actor_email)}, ${q(action)}, ${q(targetType)}, ${q(targetId)}, ${q(JSON.stringify(details))}, ${q(row.prev_hash)}, ${q(hash)});`,
  );
}
for (const u of USERS) auditEvent(u.tenant, null, "user.created", "user", u.id, { role: u.role, seed: true });

// ---------------------------------------------------------------------------
// Approved signals
// ---------------------------------------------------------------------------
function gen(tenant: string, count: number, seed: number, codeStart: number, reviewers: { id: string; email: string; name: string }[]) {
  const r = rng(seed);
  const pick = <T>(a: T[]) => a[Math.floor(r() * a.length)] as T;
  const mw = [6, 3, 4, 6, 2, 3, 2, 2, 1];
  const tot = mw.reduce((a, b) => a + b, 0);
  const cw = [5, 4, 3, 2.5, 4.5];
  const ct = cw.reduce((a, b) => a + b, 0);
  const wc = () => {
    let x = r() * ct;
    for (let i = 0; i < 5; i++) {
      x -= cw[i] as number;
      if (x < 0) return COMPS[i] as string;
    }
    return COMPS[0] as string;
  };
  const wm = () => {
    let x = r() * tot;
    for (let i = 0; i < mw.length; i++) {
      x -= mw[i] as number;
      if (x < 0) return MACROS[i] as string;
    }
    return MACROS[0] as string;
  };
  for (let i = 0; i < count; i++) {
    const macro = wm();
    const sub = pick(MAC[macro] as string[]);
    const ago = Math.floor(Math.pow(r(), 1.5) * 262) + 1;
    const comps = [wc()];
    if (r() < 0.22) {
      const c2 = wc();
      if (c2 !== comps[0]) comps.push(c2);
    }
    const g = r();
    const growth = GROWTH[g < 0.35 ? 0 : g < 0.75 ? 1 : 2] as string;
    const im = r();
    const impact = IMPACT[im < 0.3 ? 0 : im < 0.7 ? 1 : 2] as string;
    const source = pick(SOURCES);
    const action = r() < 0.5 ? "Actioned" : "Not Actioned";
    const title = `${comps.join(" and ")} ${PHRASE[sub]}`;
    const code = `SIG-${codeStart + i}`;
    const inbox = `INB-${1000 + codeStart - 1100 + i}`;
    const id = `itm_seed_${tenant}_${i}`;
    const sid = `sub_seed_${tenant}_${i}`;
    const who = pick(reviewers);
    const text = `${title}. Captured from ${source}; the analyst entered the tracker fields from the saved source before publishing.`;
    const url = `https://${source === "LinkedIn" ? "www.linkedin.com/posts" : source === "PR" ? "newsroom.example.com" : "source.example.com"}/${code.toLowerCase()}`;
    const revised = i % 5 === 0;
    const originalImpact = revised ? (IMPACT[(IMPACT.indexOf(impact) + 1) % 3] as string) : impact;
    const stream: Stream = i % 3 === 2 ? "secondary" : "primary";
    const recordId = `${stream === "primary" ? "P" : "S"}-${codeStart + i}`;
    const publisher = source === "PR" ? (comps[0] as string) : source === "LinkedIn" ? "LinkedIn" : "Pharma Technology Review";
    const TA = ["Oncology", "Immunology", "Cardiometabolic", "Neuroscience", "Rare Disease"];
    // The Phantoms fields (seeded so the Markdown is realistic; all non-confidential and invented).
    const ROLES = ["Medical Science Liaison", "Oncology KOL", "Regional Sales Director", "Market Access Lead", "Hospital Pharmacist"];
    const LOCATIONS = ["London, UK", "Basel, CH", "Boston, US", "Paris, FR", "Munich, DE"];
    const WORKSTREAMS = ["Launch readiness", "Market access", "Field force effectiveness", "Digital engagement"];
    const primaryFields: Record<string, string> = {
      record_id: recordId,
      source_role: pick(ROLES),
      source_company: comps[0] as string,
      source_location: pick(LOCATIONS),
      source_confidence: pick(["High", "Medium", "Low"]),
      workstream: pick(WORKSTREAMS),
      source_therapeutic_area: pick(TA),
      source_brand_asset: r() < 0.5 ? `${(comps[0] as string).slice(0, 2).toUpperCase()}-${100 + Math.floor(r() * 900)}` : "",
      insight_topic: sub,
      key_intelligence_question: `How is ${comps[0]} progressing on ${sub.toLowerCase()}?`,
      key_details: `${text}\n\nReported in a primary interview.`,
      key_metrics: r() < 0.5 ? `${Math.floor(r() * 40) + 5}% of respondents aware; ${Math.floor(r() * 12) + 2} sites.` : "",
    };
    const secondaryFields: Record<string, string> = {
      record_id: recordId,
      publisher,
      url,
      raw_ref: `RR-${String(codeStart + i).padStart(5, "0")}`,
      source_tier: SOURCE_TIER[stream],
      other_entities: r() < 0.4 ? "Academic partner" : "",
      therapeutic_area: pick(TA),
      assets: r() < 0.3 ? `${(comps[0] as string).slice(0, 2).toUpperCase()}-${100 + Math.floor(r() * 900)}` : "",
      products: "",
      header: `${title}.`,
      key_details: `${text}\n\nMacrotrend: ${macro} · subtrend: ${sub}.`,
      ci_perspective: `${impact} impact for competitors tracking ${macro}; ${growth.toLowerCase()} in activity.`,
    };
    const phantom = stream === "primary" ? primaryFields : secondaryFields;
    const phantomSql = Object.entries(phantom)
      .map(([k, v]) => `${q(k)}, ${v ? q(v) : "NULL"}`)
      .join(", ");
    const reviewSql = stream === "secondary" ? `, 'review_date', ${daysAgo(Math.max(0, ago - 1))}` : "";
    const values = (imp: string): string =>
      `json_object('date', ${daysAgo(ago)}, 'competitors', json(${q(JSON.stringify(comps))}), 'macrotrend', ${q(macro)}, 'subtrend', ${q(sub)}, 'title', ${q(title)}, 'growth', ${q(growth)}, 'impact', ${q(imp)}, 'source', ${q(source)}, 'action', ${q(action)}${reviewSql}, ${phantomSql})`;
    const prov = JSON.stringify(Object.fromEntries(defaultSchema(stream).columns.map((c) => [c.key, "analyst"])));
    const extraSql = `json_object(${q(DEFAULT_KEYS.source)}, ${q(source)}, ${q(DEFAULT_KEYS.action)}, ${q(action)}${reviewSql}, ${phantomSql.replace(/'record_id', '[^']*', /, "")})`;
    out.push(
      `INSERT INTO submissions (id, tenant_id, submitted_by, input_type, submitted_url, normalized_url, created_at) VALUES (${q(sid)}, ${q(tenant)}, ${q(who.id)}, 'url', ${q(url)}, ${q(url)}, ${tsAgo(ago, -60)});`,
    );
    out.push(
      `INSERT INTO intelligence_items (id, tenant_id, submission_id, code, signal_code, stream, record_id, status, version, attempts, input_type, url_key, outlet, submitted_url, final_url, received_at, submitted_by, headline, body_text, publication_date,
        draft_json, provenance_json, extraction_json, published_rev, pub_date, title, macrotrend, subtrend, growth, impact, extra_json, approved_at, approved_by, created_at, updated_at)
       VALUES (${q(id)}, ${q(tenant)}, ${q(sid)}, ${q(inbox)}, ${q(code)}, '${stream}', ${q(recordId)}, 'approved', 3, 1, 'url', ${q(url.replace(/^https:\/\/(www\.)?/, ""))}, ${q(source === "PR" ? "newsroom.example.com" : source === "LinkedIn" ? "linkedin.com" : "source.example.com")}, ${q(url)}, ${q(url)}, ${tsAgo(ago, -60)}, ${q(who.id)}, ${q(title)}, ${q(text)}, ${daysAgo(ago)},
        ${values(impact)}, ${q(prov)}, NULL, ${revised ? 2 : 1}, ${daysAgo(ago)}, ${q(title)}, ${q(macro)}, ${q(sub)}, ${q(growth)}, ${q(impact)}, ${extraSql}, ${tsAgo(ago - 1)}, ${q(who.id)}, ${tsAgo(ago, -60)}, ${tsAgo(Math.max(0, ago - 4))});`,
    );
    for (const c of comps) out.push(`INSERT INTO item_competitors (tenant_id, item_id, competitor) VALUES (${q(tenant)}, ${q(id)}, ${q(c)});`);
    out.push(
      `INSERT INTO processing_attempts (id, tenant_id, item_id, attempt, status, stage, started_at, finished_at, extraction_version, prompt_version, schema_version, provider, model, steps_json) VALUES ('att_${id}', ${q(tenant)}, ${q(id)}, 1, 'succeeded', 'needs_review', ${tsAgo(ago, -60)}, ${tsAgo(ago, -61)}, 'extract/2.0.0', NULL, NULL, 'none', NULL, '[]');`,
    );
    out.push(
      `INSERT INTO item_revisions (id, tenant_id, item_id, seq, kind, published_rev, values_json, provenance_json, changed_keys, created_by, created_at, note) VALUES ('rev_${id}_2', ${q(tenant)}, ${q(id)}, 1, 'published', 1, ${values(originalImpact)}, ${q(prov)}, '[]', ${q(who.id)}, ${tsAgo(ago - 1)}, 'Approved from Inbox · validation passed');`,
    );
    out.push(
      `INSERT INTO review_decisions (id, tenant_id, item_id, revision_id, decision, reviewer_id, decided_at, corrected_keys) VALUES ('dec_${id}', ${q(tenant)}, ${q(id)}, 'rev_${id}_2', 'approve', ${q(who.id)}, ${tsAgo(ago - 1)}, '[]');`,
    );
    auditEvent(tenant, who, "item.approved", "item", id, { signalCode: code, rev: 1, correctedKeys: [], seed: true });
    if (revised) {
      out.push(
        `INSERT INTO item_revisions (id, tenant_id, item_id, seq, kind, published_rev, values_json, provenance_json, changed_keys, created_by, created_at, note) VALUES ('rev_${id}_3', ${q(tenant)}, ${q(id)}, 2, 'published', 2, ${values(impact)}, ${q(prov)}, '["impact"]', 'u_jm', ${tsAgo(Math.max(0, ago - 4))}, 'Impact reclassified after client call');`,
      );
      auditEvent(tenant, { id: "u_jm", email: "j.morgan@example.com" }, "item.revised", "item", id, { rev: 2, changedKeys: ["impact"], seed: true });
    }
  }
}

const demoReviewers = USERS.filter((u) => ["u_ap", "u_jm", "u_so"].includes(u.id));
gen("t_demo", 78, 11, 1100, demoReviewers);
gen("t_north", 12, 29, 1100, [USERS.find((u) => u.id === "u_north_an") as (typeof USERS)[number]]);

// ---------------------------------------------------------------------------
// Inbox drafts (Needs review) — from the prototype
// ---------------------------------------------------------------------------
type Draft = { code: string; hoursAgo: number; outlet: string; url: string; kicker: string; headline: string; byline: string; paras: string[]; stream: Stream };
const INBOX: Draft[] = [
  {
    code: "INB-2207", stream: "secondary", hoursAgo: 3, outlet: "LinkedIn", url: "https://www.linkedin.com/posts/sanofi-employer-health", kicker: "LinkedIn post",
    headline: "Partnering with employers to widen access to specialty care", byline: "Sanofi",
    paras: ["Today we are announcing an agreement with a coalition of large US employers to offer selected medicines directly to covered employees, alongside a digital support program.", "The arrangement bypasses traditional benefit intermediaries and sets a single transparent price for participating employers."],
  },
  {
    code: "INB-2206", stream: "primary", hoursAgo: 4, outlet: "Press release", url: "https://newsroom.example.com/az-roche-ai-alliance", kicker: "Press release",
    headline: "AstraZeneca and Roche form pre-competitive AI alliance for target discovery", byline: "Business Wire",
    paras: ["The companies will pool de-identified screening data to train shared models for early target identification.", "Each partner retains rights to assets it develops independently using the shared models."],
  },
  {
    code: "INB-2205", stream: "primary", hoursAgo: 18, outlet: "Publication", url: "https://source.example.com/novartis-ai-academy", kicker: "Industry news",
    headline: "Novartis opens AI academy with three-tier certification", byline: "Pharma Technology Review",
    paras: ["All employees will be required to complete the foundation tier by the end of 2027.", "Advanced tiers are aimed at data scientists and functional AI leads."],
  },
  {
    code: "INB-2204", stream: "secondary", hoursAgo: 24, outlet: "Client signal", url: "https://client-portal.example.com/field-note-0924", kicker: "Client signal",
    headline: "Field team reports Pfizer piloting AI next-best-action in oncology", byline: "Submitted by client",
    paras: ["Account managers report that Pfizer representatives are using an AI assistant to prioritise HCP visits in two US regions."],
  },
];
const esc = (t: string) => t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const STEPS = JSON.stringify([
  { label: "Validate and normalise", ok: true, detail: "Normalised · seed data" },
  { label: "Destination check", ok: true, detail: "Public host · seed data" },
  { label: "Isolated capture worker", ok: true, detail: "Seed data (no network fetch)" },
  { label: "Access restrictions", ok: true, detail: "Seed data" },
  { label: "Content scan before storage", ok: true, detail: "Seed data · snapshot stored" },
  { label: "Data policy check", ok: true, detail: "Checked against the data policy · nothing sent to any external service (automatic pre-fill is off)" },
  { label: "Routed to Needs review", ok: true, detail: "Created in Inbox · every tracker field empty · analyst enters values from the saved source" },
]);
INBOX.forEach((it, i) => {
  const id = `itm_inbox_${i}`;
  const sid = `sub_inbox_${i}`;
  const who = USERS[1] as (typeof USERS)[number];
  const pubAgo = it.hoursAgo < 12 ? 1 : 2;
  const body = it.paras.join("\n\n");
  const received = `strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-${it.hoursAgo} hours')`;
  // A saved, sanitised copy of the page, as the capture pipeline would store it (D1 snapshot store).
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(it.headline)}</title><style>body{font:16px/1.6 Georgia,serif;max-width:720px;margin:32px auto;padding:0 16px;color:#222}.k{font:600 12px Arial,sans-serif;letter-spacing:.06em;text-transform:uppercase;color:#777}</style></head><body><article><div class="k">${esc(it.kicker)}</div><h1>${esc(it.headline)}</h1><p><em>${esc(it.byline)}</em></p>${it.paras.map((p) => `<p>${esc(p)}</p>`).join("")}</article></body></html>`;
  const sha = createHash("sha256").update(html).digest("hex");
  const key = `d1:t_demo/${id}/${sha}`;
  out.push(`INSERT INTO submissions (id, tenant_id, submitted_by, input_type, submitted_url, normalized_url, created_at) VALUES (${q(sid)}, 't_demo', ${q(who.id)}, 'url', ${q(it.url)}, ${q(it.url)}, ${received});`);
  out.push(
    `INSERT INTO intelligence_items (id, tenant_id, submission_id, code, stream, status, version, attempts, input_type, url_key, outlet, submitted_url, final_url, received_at, submitted_by, headline, body_text, publication_date,
      draft_json, provenance_json, extraction_json, model_warnings_json, warnings_count, created_at, updated_at)
     VALUES (${q(id)}, 't_demo', ${q(sid)}, ${q(it.code)}, '${it.stream}', 'needs_review', 2, 1, 'url', ${q(it.url.replace(/^https:\/\/(www\.)?/, ""))}, ${q(it.outlet)}, ${q(it.url)}, ${q(it.url)}, ${received}, ${q(who.id)}, ${q(it.headline)}, ${q(body)}, ${daysAgo(pubAgo)},
      ${q(JSON.stringify(it.stream === "secondary" ? { source_tier: SOURCE_TIER.secondary } : {}))}, '{}', NULL, '[]', 0, ${received}, ${received});`,
  );
  out.push(`INSERT INTO snapshot_blobs (storage_key, seq, tenant_id, data) VALUES (${q(key)}, 0, 't_demo', ${q(html)});`);
  out.push(
    `INSERT INTO source_snapshots (id, tenant_id, item_id, attempt, r2_key, sha256, raw_sha256, bytes, content_type, http_status, final_url, redirects, capture_method, single_file, encrypted, retain_until, retrieved_at)
     VALUES ('snap_${id}', 't_demo', ${q(id)}, 1, ${q(key)}, ${q(sha)}, NULL, ${Buffer.byteLength(html)}, 'text/html', 200, ${q(it.url)}, 0, 'fetch', 0, 0, NULL, ${received});`,
  );
  out.push(`UPDATE intelligence_items SET current_snapshot_id = 'snap_${id}' WHERE id = ${q(id)};`);
  out.push(
    `INSERT INTO processing_attempts (id, tenant_id, item_id, attempt, status, stage, started_at, finished_at, extraction_version, prompt_version, schema_version, provider, model, steps_json) VALUES ('att_${id}', 't_demo', ${q(id)}, 1, 'succeeded', 'needs_review', ${received}, ${received}, 'extract/2.0.0', NULL, NULL, 'none', NULL, ${q(STEPS)});`,
  );
  auditEvent("t_demo", who, "submission.created", "item", id, { code: it.code, inputType: "url", seed: true });
  auditEvent("t_demo", null, "item.routed", "item", id, { attempt: 1, prefill: "manual", seed: true });
});

// Capture log (prototype examples).
const LOG = [
  { h: 5, input: "https://newsroom.example.com/az-roche-ai-alliance?utm_source=li", final: "https://newsroom.example.com/az-roche-ai-alliance", outcome: "Captured · sent to Needs review", ok: 1 },
  { h: 20, input: "http://169.254.169.254/latest/meta-data", final: null, outcome: "Blocked · link-local / cloud metadata service (169.254.169.254)", ok: 0 },
  { h: 21, input: "https://news.example.com/login?next=/sanofi-dte", final: "https://news.example.com/login?next=/sanofi-dte", outcome: "Stopped · Login wall detected · capture stopped without bypass", ok: 0 },
  { h: 21, input: "sanofi-dte.html (SingleFile)", final: "https://news.example.com/sanofi-dte (from file metadata)", outcome: "Captured · sent to Needs review", ok: 1 },
];
LOG.forEach((l, i) =>
  out.push(`INSERT INTO capture_log (id, tenant_id, item_id, at, input, final_url, outcome, ok) VALUES ('cap_seed${i}', 't_demo', NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-${l.h} hours'), ${q(l.input)}, ${q(l.final)}, ${q(l.outcome)}, ${l.ok});`),
);

// Counters: next codes follow the seeded ones.
out.push("INSERT INTO counters (tenant_id, name, value) VALUES ('t_demo', 'inbox', 2207), ('t_demo', 'signal', 1177), ('t_north', 'inbox', 2200), ('t_north', 'signal', 1111);");

// Each published entry's Phantom: frozen as first pushed to the Tracker (migration 0012).
out.push(
  `INSERT OR IGNORE INTO phantom_snapshots (item_id, tenant_id, pub_date, title, macrotrend, subtrend, growth, impact, record_id, extra_json, competitors_json, published_rev, approved_at, approved_by, created_at)
   SELECT i.id, i.tenant_id, i.pub_date, i.title, i.macrotrend, i.subtrend, i.growth, i.impact, i.record_id, COALESCE(i.extra_json, '{}'),
          COALESCE((SELECT json_group_array(c.competitor) FROM item_competitors c WHERE c.item_id = i.id), '[]'), COALESCE(i.published_rev, 1), i.approved_at, i.approved_by, ${q(GEN_AT)}
     FROM intelligence_items i WHERE i.status = 'approved';`,
);
writeFileSync(new URL("./seed.sql", import.meta.url), out.join("\n") + "\n");
console.log(`seed.sql written: ${out.length} statements`);
